# Generated by Django 4.1.2 on 2022-11-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=50)),
                ('idiomas', models.CharField(max_length=100)),
                ('salas', models.CharField(max_length=50)),
            ],
        ),
    ]
