# Generated by Django 4.1.2 on 2022-11-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='salas',
        ),
    ]
