# Generated by Django 4.1.2 on 2022-11-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0004_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('apertura', models.DateTimeField()),
                ('cierre', models.DateTimeField()),
            ],
        ),
    ]
