# Generated by Django 4.1.2 on 2022-11-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0005_complejo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complejo',
            name='apertura',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='cierre',
        ),
        migrations.AddField(
            model_name='complejo',
            name='hora_apertura',
            field=models.SmallIntegerField(null=60),
            preserve_default=60,
        ),
        migrations.AddField(
            model_name='complejo',
            name='hora_cierre',
            field=models.SmallIntegerField(null=60),
            preserve_default=60,
        ),
        migrations.AddField(
            model_name='complejo',
            name='minutos_apertura',
            field=models.SmallIntegerField(null=60),
            preserve_default=60,
        ),
        migrations.AddField(
            model_name='complejo',
            name='minutos_cierre',
            field=models.SmallIntegerField(null=60),
            preserve_default=60,
        ),
    ]
