# Generated by Django 4.1.2 on 2022-11-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0006_remove_complejo_apertura_remove_complejo_cierre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complejo',
            name='hora_apertura',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='hora_cierre',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='minutos_apertura',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='minutos_cierre',
        ),
        migrations.AddField(
            model_name='complejo',
            name='horario_apertura',
            field=models.TimeField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complejo',
            name='horario_cierre',
            field=models.TimeField(null=True),
            preserve_default=False,
        ),
    ]
