# Generated by Django 4.1.2 on 2022-11-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0008_alter_complejo_horario_apertura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complejo',
            name='horario_apertura',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='horario_cierre',
        ),
    ]
