# Generated by Django 4.1.2 on 2022-11-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0009_remove_complejo_horario_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complejo',
            name='horario_apertura',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='complejo',
            name='horario_cierre',
            field=models.TimeField(null=True),
        ),
    ]
